$modelname      "vsh_incendio/indicator.mdl"
$scale          12
$body body01	"body.smd"
$texturegroup "indicator"
{
	{ "indicator_crits_off" }
	{ "indicator_crits_on" }
	{ "indicator_giant_off" }
	{ "indicator_giant_on" }
	{ "indicator_horklumps_off" }
	{ "indicator_horklumps_on" }
	{ "indicator_lumos_off" }
	{ "indicator_lumos_on" }
	{ "indicator_super_off" }
	{ "indicator_super_on" }
}
$surfaceprop	concrete
$cdmaterials	"vsh_incendio/models"

$sequence idle	"body.smd"